# Generated by Django 3.2.10 on 2023-01-11 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='outpass_locator_logs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_number', models.CharField(max_length=16)),
                ('user_id', models.IntegerField()),
                ('outpass_locator_staff_details_id', models.IntegerField()),
                ('inclusive_dates', models.TextField()),
                ('time_check_out', models.CharField(max_length=8)),
                ('time_check_in', models.CharField(max_length=8)),
                ('time_span_outpass', models.CharField(max_length=8)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'outpass_locator_logs',
            },
        ),
        migrations.CreateModel(
            name='outpass_locator_staff_details',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('auth_user_id', models.IntegerField()),
                ('id_number', models.CharField(max_length=16)),
                ('first_name', models.CharField(max_length=64)),
                ('middle_name', models.CharField(max_length=32)),
                ('last_name', models.CharField(max_length=32)),
                ('ext_name', models.CharField(max_length=16)),
                ('position', models.CharField(max_length=32)),
                ('status', models.IntegerField()),
                ('program', models.IntegerField()),
                ('qr_code', models.ImageField(blank=True, upload_to='outpass_locator/staff_qr_code')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'outpass_locator_staff_details',
            },
        ),
    ]
