# Generated by Django 3.2.10 on 2023-01-12 00:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('outpass_locator', '0002_alter_outpass_locator_staff_details_program'),
    ]

    operations = [
        migrations.CreateModel(
            name='outpass_locator_program',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
                ('description', models.CharField(max_length=32)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'outpass_locator_program',
            },
        ),
    ]
