# Generated by Django 3.2.10 on 2023-01-12 01:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('outpass_locator', '0004_outpass_locator_staff_details_outpass_locator_program_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='outpass_locator_staff_details',
            name='image',
            field=models.ImageField(null=True, upload_to='outpass_locator/staff_image'),
        ),
    ]
