# Generated by Django 3.2.10 on 2023-01-12 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('outpass_locator', '0006_outpass_locator_staff_details_current_outpass_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='outpass_locator_logs',
            name='time_check_in',
            field=models.CharField(max_length=16),
        ),
        migrations.AlterField(
            model_name='outpass_locator_logs',
            name='time_check_out',
            field=models.CharField(max_length=16),
        ),
        migrations.AlterField(
            model_name='outpass_locator_logs',
            name='time_span_outpass',
            field=models.CharField(max_length=16),
        ),
    ]
