# Generated by Django 3.2.10 on 2023-01-20 01:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('outpass_locator', '0007_auto_20230112_1540'),
    ]

    operations = [
        migrations.AddField(
            model_name='outpass_locator_logs',
            name='month',
            field=models.CharField(max_length=12, null=True),
        ),
    ]
