# Generated by Django 3.2.10 on 2023-01-20 03:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('outpass_locator', '0008_outpass_locator_logs_month'),
    ]

    operations = [
        migrations.AddField(
            model_name='outpass_locator_staff_details',
            name='full_name',
            field=models.CharField(max_length=128, null=True),
        ),
    ]
