# Generated by Django 3.2.10 on 2023-02-02 02:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('outpass_locator', '0009_outpass_locator_staff_details_full_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='outpass_locator_logs',
            name='outpass_type_id',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='outpass_locator_logs',
            name='place_visited',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='outpass_locator_logs',
            name='remarks',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='outpass_locator_staff_details',
            name='outpass_type_id',
            field=models.IntegerField(null=True),
        ),
    ]
