# Generated by Django 3.2.10 on 2023-02-02 03:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('outpass_locator', '0012_auto_20230202_1117'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='outpass_locator_logs',
            name='place_visited',
        ),
        migrations.AddField(
            model_name='official_outpass_locator_logs',
            name='if_approved',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='outpass_locator_logs',
            name='if_approved',
            field=models.IntegerField(null=True),
        ),
    ]
