# Generated by Django 3.2.10 on 2023-02-02 04:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('outpass_locator', '0013_auto_20230202_1134'),
    ]

    operations = [
        migrations.RenameField(
            model_name='outpass_locator_staff_details',
            old_name='current_outpass_id',
            new_name='current_official_outpass_id',
        ),
        migrations.AddField(
            model_name='outpass_locator_staff_details',
            name='current_personal_outpass_id',
            field=models.IntegerField(null=True),
        ),
    ]
